V2
criteo-cookbooks/gobgp pull request #3
Opened 2019-04-08 12:58 UTC by Koaxiel

2019-04-08 17:37 UTC, Annih requested changes

2019-04-08 17:37 UTC, Annih commented on recipes/default.rb
> +  remote_file uri do
Could you add a way to optionally add the file checksum?
Otherwise you are going to have issues with our internal "remote_file" mechanism

2019-04-10 08:17 UTC, Annih approved these changes

2019-04-10 09:53 UTC, Koaxiel commented on recipes/default.rb
> +  remote_file uri do
Done

2019-04-10 11:18 UTC, merged